### ISSUE TITLE
[contribute interface] zoo images needs often a refresh to appears  (firefox)

### ISSUE THREAD

**Issue by verovs** [DiSSCo/herbonauts#13]
On chrome it's fine but on firefox I need to empty the cache to see the images.
http://lesherbonautes.mnhn.fr/test/missions/5268342
this mission have 2 plant specimens (which arn't tuiled anymore so aren't showing, it's fine) and 3 bird specimens.
Not every time but a lot of time I need to clear the cache for the birds to appears, even if I just saw them. I clicked on "specimen suivant"  a lot to check if they will appears.sometimes they  will, sometimes not.
maybe it's only for my browser?  The past 2 days zoo images were displayed just fine

![capture d ecran de 2018-10-11 14-28-37](https://user-images.githubusercontent.com/22638189/46804056-ff16b480-cd61-11e8-8e4b-1a649533de56.png)
no images but seems everything is fine

**Comment by yall** [comment]
I just tested and there's an error getting the list of images for some specimens. I'll test on my side with same specimens.

**Comment by verovs** [comment]
not reproducible anymore !
