### ISSUE TITLE
[contribution template] when i add the geoloc manually, if i have more than 4 decimales it goes on antarctica

### ISSUE THREAD

**Issue by verovs** [DiSSCo/herbonauts#16]
As the title.I don't know if it worked correctly before.
If i search on the research ("place") box, I can have results with lots of decimals without problem.
But if i write the number in the fields with my little hand it stop working after the 4 digit et the cursor goes to bottom-center in Antarctica.
coord : 15.300355 , 166.91
 -15,300355 > Antarctica 
 -15,30035 > Antarctica 
-15,3003  > ok, somewhere in the see.
Maybe we could "tell" the geolocate service to just forget the number when it goes beyond his comprehension ? Something like this :)

**Comment by yall** [comment]
Hi Vero, I can't reproduce. 
With the same coordinates, the pin is still at the same place (tested on Chrome & Firefox).

**Comment by verovs** [comment]
Ok, I did reproduce it. But it's not exactly what I wrote. The key factor is the **comma**
In fact it work correctly when it's written with a period and not a comma. I didn't realize it the first time. 
Ex In the first field i write some stuff (I dont touch the second filed)
If i write 15.300355 I'm on the map
If i write (or even if i copy/paste) 15,300355, I'm now in Artica (and not Antarctica anymore)
(Firefox 67.0.2)
link for test : http://lesherbonautes.mnhn.fr/test/missions/5272941/specimens/5273288
same for chrome (V.72, not the last), it stop working  after the 4 digit et the cursor goes to top-center in Arctica.
I dont know if that's should work with coma but that's odd that it work right for 1+ 4 digit and stop after

**Comment by yall** [comment]
OK. I got it now. The input field accepts multiple format for coord : decimal, deg + decimal minutes, deg + minutes + seconds.

The issue is for decimal format: it accepts only "x.yyy" format and evaluate "x,yyy" as "x deg yyy minutes". I'm fixing it

**Comment by yall** [comment]
Fixed

**Comment by marcPignal** [comment]
Je n'ai pas trop suivi. Mais serait-il possible pour que les coordonnées acceptent indifféremment, les points et les virgules?  Jonathan, tu as corrigé, cela signifie que "x,yyy" est compris comme"x deg yyy minutes"? ou bien c'est que c'est changé, justement?

**Comment by yall** [comment]
@marcPignal c'est ce qui est changé. Avant la seule façon de saisir au format décimal c'était avec x.yyy, le formulaire comprenait tout autre caractère que le point comme une séparation du format deg/min. Aujourd'hui x.yyy et x,yyy seront interprétés comme des degrés au format décimal. Si on ajoute un autre caractère ou un espace puis d'autre chiffres (ex "12.34 56"), on passe au format deg/min/sec. J'espère t'avoir éclairé.

**Comment by verovs** [comment]
it works
