### ISSUE TITLE
[transcribe layout] Map search: no more completion in the search box

### ISSUE THREAD

**Issue by verovs** [DiSSCo/herbonauts#2]
There is a little difference with before.
When looking for a locality, on the map panel, if i click on one of the result it jump to it but does'nt complete the search box

I'm not sure how to say this clearly so i join a picture for better explanation.
![differencewithimgsandwords](https://user-images.githubusercontent.com/22638189/44989633-c4fe0a00-af8e-11e8-8bdd-5ec95b70533e.png)

Why it matters: users usually copy/paste this info in the "precision" field in geolocalisation fields. When a conflict pop up the precision label is showing and we can easily see if the conflict is just because the result chosen is slightly different (virgule, etc.).

Although this not seems to be a real issue our users will miss it cause they have habits :(

**Comment by yall** [comment]
Hi Vero. No problem, I'll fix this.

**Comment by verovs** [comment]
this is not working. and my " geolocate curseur" isn't moving.
It only moves if i clic on it and put it somewhere in the map myself, but not with the search result. 
i tried 2 users, but i tried only with firefox

**Comment by verovs** [comment]
it works perfectly :)
