### ISSUE TITLE
Spécimens sans information de récolte

### ISSUE THREAD

**Issue by marcPignal** [DiSSCo/herbonauts#20]
sélection des images: quand on clique " Spécimens sans information de récolte", on trouve plus images que quand la case n'est pas cliquée (ce devrait etre l'inverse

**Comment by verovs** [comment]
on voit bien les nouveaux filtres, ils ont en plus l'air de fonctionner dans la console (?)
![Capture d’écran de 2019-07-03 17-19-37](https://user-images.githubusercontent.com/22638189/60604668-6a088f80-9db8-11e9-8e49-b15b860d8dbe.png)
![Capture d’écran de 2019-07-03 17-19-16](https://user-images.githubusercontent.com/22638189/60604676-6bd25300-9db8-11e9-9c45-f5759713a778.png)

Mais les résultats de la recherche ne s'actualisent pas et semblent correspondre aux spécimens sans infos de récolte @yall 

![Capture d’écran de 2019-07-03 16-52-39](https://user-images.githubusercontent.com/22638189/60604833-b358df00-9db8-11e9-8e98-39e426ab7d4e.png)

**Comment by yall** [comment]
Peut-être un problème de cache de navigateur. Le fichier http://lesherbonautes.mnhn.fr/v22/js/herbonautes-app-chef.js a été modifié.
Peux-tu tester en forçant le rafraichissement (Ctrl + Shift + R) ?

**Comment by verovs** [comment]
MAIS je l'avais fait pourtant !  :S 
En tout cas, en re vidant le cache ça marche, évidemment. C'est bon pour moi. 
Je laisse ouvert ici pour que @marcPignal aille voir si cela lui convient :)
