### ISSUE TITLE
txt mail parrainage

### ISSUE THREAD

**Issue by verovs** [DiSSCo/herbonauts#22]
![Capture d’écran de 2019-07-01 15-58-54](https://user-images.githubusercontent.com/22638189/60442824-2d9f2d00-9c1a-11e9-817e-14634af4cc68.png)

+ votre

**Comment by verovs** [comment]
### Version courte : 
(User) vous invite à rejoindre Les Herbonautes.
Les Herbonautes (lien http://lesherbonautes.mnhn.fr) est un programme vous permettant d'explorer et de documenter les collections des herbiers français.  A vous d'explorer ces plantes et leurs étiquettes pour déterminer quand et où elles ont été récoltées. 

**Rejoindre Les Herbonautes** (strong)
Pour vous inscrire suivez ce lien (link  - à partir de suivez si possible)
Si le lien ne s'ouvre pas copiez cette adresse dans votre navigateur xxxxxxxxxxx

A bientôt sur Les Herbonautes !


### Version longue
User vous invite à rejoindre Les Herbonautes.
Les Herbonautes (lien http://lesherbonautes.mnhn.fr) est un programme vous permettant d'explorer et de documenter les collections des herbiers français.  
A vous d'explorer ces plantes et leurs étiquettes pour déterminer quand et où elles ont été récoltées. En renseignant les informations qu'elles contiennent vous permettez à tous, chercheurs et citoyens, d'avoir accès à ces données primordiales pour mieux connaître la biodiversité,  mesurer et prévoir son érosion.
A vous de jouer ! 

**Rejoindre Les Herbonautes** (strong)
Pour vous inscrire suivez ce lien (link  - à partir de suivez si possible)
Si le lien ne s'ouvre pas copiez cette adresse dans votre navigateur xxxxxxxxxxx

A bientôt sur Les Herbonautes !

**Comment by simoncha** [comment]
une petite préférence pour la version longue ...

**Comment by marcPignal** [comment]
Supprimer "français", on a fait des missions avec le Canada, et nous espérons bien avoir des coopérations avec tous les herbiers qui le souhaitent. 
"Les Herbonautes (lien http://lesherbonautes.mnhn.fr) est un programme vous permettant d'explorer et de documenter les  herbiers des collections naturalistes."

**Comment by verovs** [comment]
ok on part alors sur cette version @yall 

_User_  vous invite à rejoindre Les Herbonautes.
Les Herbonautes _(lien http://lesherbonautes.mnhn.fr)_ est un programme vous permettant d'explorer et de documenter les herbiers des collections naturalistes.
A vous d'explorer ces plantes et leurs étiquettes pour déterminer quand et où elles ont été récoltées. En renseignant les informations qu'elles contiennent vous permettez à tous, chercheurs et citoyens, d'avoir accès à ces données primordiales pour mieux connaître la biodiversité, mesurer et prévoir son érosion.
A vous de jouer !

Rejoindre Les Herbonautes _(strong)_
Pour vous inscrire suivez ce lien _(link - à partir de suivez si possible)_
Si le lien ne s'ouvre pas copiez cette adresse dans votre navigateur xxxxxxxxxxx

A bientôt sur Les Herbonautes !

**Comment by verovs** [comment]
![Capture d’écran de 2019-07-03 16-14-57](https://user-images.githubusercontent.com/22638189/60598889-cade9a80-9dad-11e9-8dbb-25ae4883fc0d.png)
:)
