### ISSUE TITLE
invite to join a mission doesn't change if already joined

### ISSUE THREAD

**Issue by GwLB** [DiSSCo/herbonauts#6]
Very little issue, but the mission display page doesn't seems to remember the user account logged already joined the mission. 
![bug1](https://user-images.githubusercontent.com/38424237/46617944-71975280-cb1e-11e8-9bd9-242f70f3fcef.png)

**Comment by GwLB** [comment]
Same occurs for mission to come and mission already opened, whatever if the account is owner of the mission or not.

**Comment by verovs** [comment]
same in prod. i'm already a member of the first one
![capture d ecran de 2018-10-09 12-01-36](https://user-images.githubusercontent.com/22638189/46662240-2d0dc480-cbbb-11e8-9b06-e092e4604742.png)

**Comment by yall** [comment]
It has always worked like this. For now it's only a link to the mission page.

**Comment by verovs** [comment]
ah oui c'est vrai !
