### ISSUE TITLE
Image demultiplication while tiling process

### ISSUE THREAD

**Issue by GwLB** [DiSSCo/herbonauts#8]
Tiling process seems in some cases to multiply images number. In example : EC703 (MNHN-EC-EC703).
![bug_img_multiples](https://user-images.githubusercontent.com/38424237/46652506-85d16300-cba3-11e8-9fc0-7f0ef91af86e.jpg)
In this example, 2 images are to be find in Explore.recolnat ( https://explore.recolnat.org/occurrence/00BFD13734844500984A8CE7F4956742 ). It shouldn't influence, but on science.mnhn (source database through a web-browser) it is the same ( https://science.mnhn.fr/institution/mnhn/collection/ec/item/ec703 ).
Is it because the specimen has several scientific names / litterature linked to it ?

**Comment by GwLB** [comment]
For EC708, the label image was copied 4 times and the specimen one 3 times (different amount for the 2 images)

**Comment by yall** [comment]
Hi. It seems it's not duplicated during tiling process. Specimens are imported from elasticsearch index and it seems images are already duplicated in the index (https://search.recolnat.org/zoologie/specimens/0B2325D7655E403BB1FA6A60EDF4A84C for EC708). The need is to "deduplicate" images while importing.

**Comment by verovs** [comment]
I added 3 birds (one same as in "mix mission") in this mission : http://lesherbonautes.mnhn.fr/test/missions/5268342
Need to wait tomorrow to check the "simple tiling". 
(this is for me to remember where i added them!).
Since all zoo's metadata have the same pb (16 img bird from #9 : https://search.recolnat.org/zoologie/specimens/04CBBE8957BC41679A45CF5111121EDF  ) do we need to report it to Julien ? @simoncha

**Comment by simoncha** [comment]
Julien is aware of the duplication. Specimens with several determinations appear several times in recolnat index. The version I deployed this morning has a fix to correct it on herbonautes side

**Comment by verovs** [comment]
ok! Dead birds only have one set of images now 
http://lesherbonautes.mnhn.fr/test/missions/5268342/specimens/5272689
http://lesherbonautes.mnhn.fr/test/missions/5268342/specimens/5272709
![capture d ecran de 2018-10-11 14-00-35](https://user-images.githubusercontent.com/22638189/46802732-79453a00-cd5e-11e8-8813-63952364a5bb.png)
