### ISSUE TITLE
[contribute interface] multi images in strange order

### ISSUE THREAD

**Issue by verovs** [DiSSCo/herbonauts#9]
http://lesherbonautes.mnhn.fr/test/missions/5270567/specimens/5271623
In this specimen the number of each images arn't in a logical order: 14-15-16-1-2-3-4-5-6-7-8-9-10-11-12
1 to 8 is a serie
9 to 16 is the duplicate.
That's maybe linked to #8 ?
![capture d ecran de 2018-10-09 11-46-46](https://user-images.githubusercontent.com/22638189/46661266-241bf380-cbb9-11e8-8d00-3599327357b3.png)

**Comment by yall** [comment]
Order is an issue. I'll fix it.
Duplication is indeed the same problem as #8.

**Comment by verovs** [comment]
Ok for the order.
For the duplicate I will check on other databases and use #8 if needed 
![capture d ecran de 2018-10-10 11-18-53](https://user-images.githubusercontent.com/22638189/46727002-ec2bb380-cc7f-11e8-8bcc-dba84d5015e2.png)
